# -*- coding: utf-8 -*-
# Generated by the protocol buffer compiler.  DO NOT EDIT!
# source: DrillGameRecord.proto
"""Generated protocol buffer code."""
from google.protobuf import descriptor as _descriptor
from google.protobuf import message as _message
from google.protobuf import reflection as _reflection
from google.protobuf import symbol_database as _symbol_database
# @@protoc_insertion_point(imports)

_sym_db = _symbol_database.Default()




DESCRIPTOR = _descriptor.FileDescriptor(
  name='DrillGameRecord.proto',
  package='drillai',
  syntax='proto3',
  serialized_options=None,
  create_key=_descriptor._internal_create_key,
  serialized_pb=b'\n\x15\x44rillGameRecord.proto\x12\x07\x64rillai\"\xdf\x01\n\nGameRecord\x12\x13\n\x0bgarbageSeed\x18\x01 \x01(\x06\x12\x11\n\tpieceSeed\x18\x02 \x01(\x06\x12\x14\n\x0cplayedPieces\x18\x03 \x03(\x07\x12-\n\x05steps\x18\x04 \x03(\x0b\x32\x1e.drillai.GameRecord.RecordStep\x1a\x64\n\nRecordStep\x12\x12\n\nfieldCells\x18\x01 \x03(\x08\x12\x12\n\ntetrominos\x18\x02 \x03(\x07\x12\x0f\n\x07\x61\x63tions\x18\x03 \x03(\x07\x12\x0e\n\x06priors\x18\x04 \x03(\x02\x12\r\n\x05value\x18\x05 \x01(\x02\x62\x06proto3'
)




_GAMERECORD_RECORDSTEP = _descriptor.Descriptor(
  name='RecordStep',
  full_name='drillai.GameRecord.RecordStep',
  filename=None,
  file=DESCRIPTOR,
  containing_type=None,
  create_key=_descriptor._internal_create_key,
  fields=[
    _descriptor.FieldDescriptor(
      name='fieldCells', full_name='drillai.GameRecord.RecordStep.fieldCells', index=0,
      number=1, type=8, cpp_type=7, label=3,
      has_default_value=False, default_value=[],
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR,  create_key=_descriptor._internal_create_key),
    _descriptor.FieldDescriptor(
      name='tetrominos', full_name='drillai.GameRecord.RecordStep.tetrominos', index=1,
      number=2, type=7, cpp_type=3, label=3,
      has_default_value=False, default_value=[],
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR,  create_key=_descriptor._internal_create_key),
    _descriptor.FieldDescriptor(
      name='actions', full_name='drillai.GameRecord.RecordStep.actions', index=2,
      number=3, type=7, cpp_type=3, label=3,
      has_default_value=False, default_value=[],
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR,  create_key=_descriptor._internal_create_key),
    _descriptor.FieldDescriptor(
      name='priors', full_name='drillai.GameRecord.RecordStep.priors', index=3,
      number=4, type=2, cpp_type=6, label=3,
      has_default_value=False, default_value=[],
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR,  create_key=_descriptor._internal_create_key),
    _descriptor.FieldDescriptor(
      name='value', full_name='drillai.GameRecord.RecordStep.value', index=4,
      number=5, type=2, cpp_type=6, label=1,
      has_default_value=False, default_value=float(0),
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR,  create_key=_descriptor._internal_create_key),
  ],
  extensions=[
  ],
  nested_types=[],
  enum_types=[
  ],
  serialized_options=None,
  is_extendable=False,
  syntax='proto3',
  extension_ranges=[],
  oneofs=[
  ],
  serialized_start=158,
  serialized_end=258,
)

_GAMERECORD = _descriptor.Descriptor(
  name='GameRecord',
  full_name='drillai.GameRecord',
  filename=None,
  file=DESCRIPTOR,
  containing_type=None,
  create_key=_descriptor._internal_create_key,
  fields=[
    _descriptor.FieldDescriptor(
      name='garbageSeed', full_name='drillai.GameRecord.garbageSeed', index=0,
      number=1, type=6, cpp_type=4, label=1,
      has_default_value=False, default_value=0,
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR,  create_key=_descriptor._internal_create_key),
    _descriptor.FieldDescriptor(
      name='pieceSeed', full_name='drillai.GameRecord.pieceSeed', index=1,
      number=2, type=6, cpp_type=4, label=1,
      has_default_value=False, default_value=0,
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR,  create_key=_descriptor._internal_create_key),
    _descriptor.FieldDescriptor(
      name='playedPieces', full_name='drillai.GameRecord.playedPieces', index=2,
      number=3, type=7, cpp_type=3, label=3,
      has_default_value=False, default_value=[],
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR,  create_key=_descriptor._internal_create_key),
    _descriptor.FieldDescriptor(
      name='steps', full_name='drillai.GameRecord.steps', index=3,
      number=4, type=11, cpp_type=10, label=3,
      has_default_value=False, default_value=[],
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR,  create_key=_descriptor._internal_create_key),
  ],
  extensions=[
  ],
  nested_types=[_GAMERECORD_RECORDSTEP, ],
  enum_types=[
  ],
  serialized_options=None,
  is_extendable=False,
  syntax='proto3',
  extension_ranges=[],
  oneofs=[
  ],
  serialized_start=35,
  serialized_end=258,
)

_GAMERECORD_RECORDSTEP.containing_type = _GAMERECORD
_GAMERECORD.fields_by_name['steps'].message_type = _GAMERECORD_RECORDSTEP
DESCRIPTOR.message_types_by_name['GameRecord'] = _GAMERECORD
_sym_db.RegisterFileDescriptor(DESCRIPTOR)

GameRecord = _reflection.GeneratedProtocolMessageType('GameRecord', (_message.Message,), {

  'RecordStep' : _reflection.GeneratedProtocolMessageType('RecordStep', (_message.Message,), {
    'DESCRIPTOR' : _GAMERECORD_RECORDSTEP,
    '__module__' : 'DrillGameRecord_pb2'
    # @@protoc_insertion_point(class_scope:drillai.GameRecord.RecordStep)
    })
  ,
  'DESCRIPTOR' : _GAMERECORD,
  '__module__' : 'DrillGameRecord_pb2'
  # @@protoc_insertion_point(class_scope:drillai.GameRecord)
  })
_sym_db.RegisterMessage(GameRecord)
_sym_db.RegisterMessage(GameRecord.RecordStep)


# @@protoc_insertion_point(module_scope)
